# Use an official Node.js runtime as a parent image for development
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Expose port
EXPOSE 3001

# Start the app
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0"]
