services:  
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGODB_DB=mongodb
      - MONGODB_PORT=27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: chat-backend-dev
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017
    ports:
      - "8000:8000"
      - "9229:9229"  # For debugging tools like VSCode
    volumes:
      - ./backend/src:/usr/src/app/src
      - /usr/src/app/node_modules
      - ./backend:/app  # Mount the entire project (optional)
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: chat-frontend-dev
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

# Add the volume definition at the top level
volumes:
  mongodb_data: